Criando a primeira versão do modulo de network GCP da mentoriaiac
mentoriaiac/iac-modulo-rede-gcp pull request #2
Opened 2021-06-16 00:34 UTC by Rehzende

2021-06-19 14:28 UTC, gomex commented on variables.tf
> +}
Queremos em branco mesmo ou queremos forçar a pessoa a especificar?

2021-06-19 14:28 UTC, gomex commented on variables.tf
> +}
Esse aqui podemos colocar um default com um nome real, né? Não é como a pessoa precisasse informar o nome do firewall, correto?

2021-06-19 14:28 UTC, gomex commented on variables.tf
> +}
Queremos em branco mesmo ou queremos forçar a pessoa a especificar?

2021-06-20 14:11 UTC, gomex requested changes

2021-06-20 14:11 UTC, gomex commented on Makefile
> +deploy: dummy
Falta uma linha em branco aqui.

2021-06-20 14:11 UTC, gomex commented
Ta ficando MUITO bom. Parabéns ;)

2021-06-20 17:07 UTC, gomex requested changes
Está ficando muito bom, só tenho algumas sugestões.

2021-06-20 17:07 UTC, gomex commented on main.tf
> +}
Podemos definir a arquitetura no módulo, que tal? Ja deixar certo que seria uma pública e uma privada.

2021-06-20 18:29 UTC, gomex commented on variables.tf
> +}
Decidimos remover o valor default para todos as variáveis que precisam ser especificadas.

2021-06-20 18:30 UTC, gomex commented on variables.tf
> +}
Colocar o type e uma validação.

2021-06-20 18:30 UTC, gomex commented on variables.tf
> +}
Colocar o type.

2021-06-20 18:31 UTC, gomex reviewed
Colocar o type em todas variáveis e condição nas que forem mais pertinentes.

2021-07-09 13:37 UTC, edsoncelio commented on output.tf
> +  value     = google_compute_network.vpc_network.id
Acho que valeria adicionar um `description` aqui

2021-07-09 13:38 UTC, edsoncelio commented on output.tf
> +output "subnets_id" {
Acho que valeria adicionar um `description` aqui

2021-07-10 20:30 UTC, Rehzende commented on output.tf
> +output "subnets_id" {
Ajustado

2021-07-10 20:30 UTC, Rehzende commented on output.tf
> +  value     = google_compute_network.vpc_network.id
Ajustado

2021-07-11 18:35 UTC, gomex requested changes
Precisa melhorar o README apenas.

2021-07-18 13:22 UTC, merged