Pull Request para resolver a issue #3 https://github.com/mentoriaiac/iac-modulo-rede-gcp/issues/3
mentoriaiac/iac-modulo-rede-gcp pull request #4
Opened 2021-08-04 00:38 UTC by nerdtux

# Criar testes automatizados para o modulo #3

O PR cria CI para testar iac-modulo-rede-gcp.

- [ ] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [ ] Dê um titulo que expresse o objetivo do PR
- [ ] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [ ] Descreva o objetivo do PR
- [ ] Inclua links relevantes para a sua modificação/sugestão/correção
- [ ] Descreva um passo-a-passo para testar o seu PR

## Issue

#3 

## Objetivo

## Referências

## Como testar

Desafios a serem resolvidos:
   Retirar o passo de autenticar na GCP usando o navegador

2021-08-10 21:45 UTC, nerdtux commented
Testes para o Terraform do módulo de redes.

2021-09-26 14:48 UTC, gomex requested changes
Está ficando MUITO bom, mas falta alguns detalhes e precisamos tomar uma decisão em um ponto.

2021-09-26 14:48 UTC, gomex commented on how-to-use-this-module/terrafile.tf
> +  project  = "nomedoprojeto"
Nessa linha temos o seguinte problema. Como isso aqui é estático, precisamos criar o projeto com nome "nomedoprojeto" em nossa conta pra validar esse terraform. 

IMHO (In My Humble Opinion - Em minha humilde opinião) eu acho que temos dois caminhos:

- Colocar um nome mais genérico para testes (Caminho mais fácil. Precisaria trocar a documentação pra deixar claro isso)
- Colocar o nome do projeto como variável do terraform, e carregar isso como variável de ambiente. (Adiciona complexidade para quem vai testar o módulo local, mas não muito. Eu gosto muito dessa opção aqui, ainda mais se colocarmos pra o terraform rodar em docker, com make, fica tranquilo assim.) 
- Criar uma pasta focada para teste, com valores estáticos para teste (Eu gosto menos dessa opção)

2021-09-26 14:48 UTC, gomex commented on .github/workflows/ci_plan.yml
> +        run: terraform apply -auto-approve
Porque não coloca assim:

```
terraform plan -out plano
```

E na outra step:

```
terraform apply "plano"
```

2021-09-26 14:48 UTC, gomex commented on .gitignore
> +key.json
Precisa colocar o arquivo usado no plan aqui.

2021-09-26 14:48 UTC, gomex commented on AUTENTICACAO_GCLOUD.md
> +``glcoud projects lis`t``
Typo

2021-10-31 20:51 UTC, nerdtux commented
Mudaremos o conceito de implementação de Ci/CD.
Vou reiniciar do 0 (zero)

2021-10-31 20:51 UTC, closed without merging